package com.sonnguyen.webdochoioto.entity;
// Generated Feb 29, 2020 11:40:05 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "db_tbyte")
public class Orders implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private User user;
	private Boolean status;
	private Date orderDate;
	private int totalPrice;
	private int quantity;
	private Set<ProductOrdersDetails> productOrdersDetailses = new HashSet<ProductOrdersDetails>(0);

	public Orders() {
	}

	public Orders(User user, Date orderDate, int totalPrice, int quantity) {
		this.user = user;
		this.orderDate = orderDate;
		this.totalPrice = totalPrice;
		this.quantity = quantity;
	}

	public Orders(User user, Boolean status, Date orderDate, int totalPrice, int quantity,
			Set<ProductOrdersDetails> productOrdersDetailses) {
		this.user = user;
		this.status = status;
		this.orderDate = orderDate;
		this.totalPrice = totalPrice;
		this.quantity = quantity;
		this.productOrdersDetailses = productOrdersDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 26)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "total_price", nullable = false)
	public int getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<ProductOrdersDetails> getProductOrdersDetailses() {
		return this.productOrdersDetailses;
	}

	public void setProductOrdersDetailses(Set<ProductOrdersDetails> productOrdersDetailses) {
		this.productOrdersDetailses = productOrdersDetailses;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
