package com.sonnguyen.webdochoioto.entity;
// Generated Feb 29, 2020 11:40:05 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "db_tbyte")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer productId;
	private Brand brand;
	private Category category;
	private String name;
	private Float discount;
	private String description;
	private Integer price;
	private Integer soLuong;
	private Set<Images> imageses = new HashSet<Images>(0);
	private Set<ProductOrdersDetails> productOrdersDetailses = new HashSet<ProductOrdersDetails>(0);

	public Product() {
	}

	public Product(Brand brand, Category category) {
		this.brand = brand;
		this.category = category;
	}

	public Product(Brand brand, Category category, String name, Float discount, String description, Integer price,
			Integer soLuong, Set<Images> imageses, Set<ProductOrdersDetails> productOrdersDetailses) {
		this.brand = brand;
		this.category = category;
		this.name = name;
		this.discount = discount;
		this.description = description;
		this.price = price;
		this.soLuong = soLuong;
		this.imageses = imageses;
		this.productOrdersDetailses = productOrdersDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brand_id", nullable = false)
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "discount", precision = 12, scale = 0)
	public Float getDiscount() {
		return this.discount;
	}

	public void setDiscount(Float discount) {
		this.discount = discount;
	}

	@Column(name = "description", columnDefinition = "TEXT")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "soLuong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Images> getImageses() {
		return this.imageses;
	}

	public void setImageses(Set<Images> imageses) {
		this.imageses = imageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductOrdersDetails> getProductOrdersDetailses() {
		return this.productOrdersDetailses;
	}

	public void setProductOrdersDetailses(Set<ProductOrdersDetails> productOrdersDetailses) {
		this.productOrdersDetailses = productOrdersDetailses;
	}

}
