package com.sonnguyen.webdochoioto.entity;
// Generated Feb 29, 2020 11:40:05 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductOrdersDetails generated by hbm2java
 */
@Entity
@Table(name = "product_orders_details", catalog = "db_tbyte")
public class ProductOrdersDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProductOrdersDetailsId id;
	private Orders orders;
	private Product product;

	public ProductOrdersDetails() {
	}

	public ProductOrdersDetails(ProductOrdersDetailsId id, Orders orders, Product product) {
		this.id = id;
		this.orders = orders;
		this.product = product;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ordersId", column = @Column(name = "orders_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
	public ProductOrdersDetailsId getId() {
		return this.id;
	}

	public void setId(ProductOrdersDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orders_id", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
