package com.sonnguyen.webdochoioto.entity;
// Generated Feb 16, 2020 6:59:26 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "db_ban_hang_oto")
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String code;
	private Set<Users> userses = new HashSet<Users>(0);

	public Roles() {
	}

	public Roles(int id) {
		this.id = id;
	}

	public Roles(int id, String name, String code, Set<Users> userses) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.userses = userses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "roles_has_users", catalog = "db_ban_hang_oto", joinColumns = {
			@JoinColumn(name = "roles_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "users_id", nullable = false, updatable = false) })
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
